@startuml
title Medicamente Оплата услуг Data Flow Diagrams

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(patient, "Пациент", "Пациент оплачивающий услуги")
Person(accountant, "Бухгалтер", "Бухгалтер, обрабатывающий платеж")

System(payment, "Оплата услуг", "Оставляет платежные данные")
System(kkm, "ККМ", "Процесс проведения платежа")
System(paymentData, "Хранилище информации о платежах", "Хранит информацию о платежах", "Шифрование данных; Тэг FIN")
System(dataLake, "Хранилище данных для аналитики", "Хранит обезличенные данные")

Rel(patient, payment, "Вносит оплату")
Rel(payment, kkm, "Автоматически передает данные", "Шифрование (TLS 1.2)")
Rel(kkm, paymentData, "Сохраняет информацию о платеже", "Шифрование (TLS 1.2)")
Rel(accountant, paymentData, "Обрабатывает платежи", "RBAC")

Rel(paymentData, dataLake, "Автоматически передает данные", "Шифрование (TLS 1.2)" )

@enduml