@startuml
title Medicamente Учет ТМЦ Data Flow Diagrams

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(warehouseKeeper, "Сотрудник склада", "Сотрудник склада, ведущий приме ТМЦ")
Person(accountant, "Бухгалтер", "Бухгалтер, обрабатывающий платежную информацию")

System(warehouseData, "Хранилище информации о ТМЦ", "Хранит информацию о ТМЦ", "Тэг PUB")
System(paymentData, "Хранилище информации о платежах", "Хранит информацию о платежах", "Шифрование данных; Тэг FIN")
System(dataLake, "Хранилище данных для аналитики", "Хранит обезличенные данные")

Rel(warehouseKeeper, warehouseData, "Ведет учет ТМЦ")
Rel(warehouseData, paymentData, "Передает информацию о платежах", "Шифрование (TLS 1.2)")
Rel(accountant, paymentData, "Обрабатывает платежную информацию о ТМЦ")

Rel(paymentData, dataLake, "Автоматически передает данные", "Шифрование (TLS 1.2)" )

@enduml